language: python

matrix:
  include:
    - python: 2.7
      env:
        - COVERAGE=false
        - ARGS="--verbose"
    - python: 3.4
      env:
        - COVERAGE=false
        - ARGS="--mpl --verbose"
    - python: 3.5
      env:
        - COVERAGE=false
        - ARGS="--mpl --verbose"
    - python: 3.5
      env:
        - COVERAGE=true
        - ARGS="--mpl --verbose --pep8"

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes true
  - conda config --add channels conda-forge
  - conda update conda
  - conda install nomkl

install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.

  - conda create -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install docopt requests pyyaml
  - conda install numpy scipy matplotlib geopandas pandas rasterio fiona gdal --channel=conda-forge
  - conda install pytest mock pytest-mpl coverage pytest-pep8 --channel=conda-forge
  - pip install codecov
  - pip install .

script:
  - python check_gisutils.py ${ARGS}

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage run --source gisutils check_gisutils.py;
      coverage report -m;
      codecov;
    fi
